# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signum_v2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SigNum = QtWidgets.QLabel(self.centralwidget)
        self.SigNum.setObjectName("SigNum")
        self.verticalLayout_4.addWidget(self.SigNum)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LiveVideo = QtWidgets.QLabel(self.centralwidget)
        self.LiveVideo.setMinimumSize(QtCore.QSize(321, 311))
        self.LiveVideo.setText("")
        self.LiveVideo.setObjectName("LiveVideo")
        self.verticalLayout_3.addWidget(self.LiveVideo)
        self.Widget_Play_and_Stop = QtWidgets.QWidget(self.centralwidget)
        self.Widget_Play_and_Stop.setMaximumSize(QtCore.QSize(321, 53))
        self.Widget_Play_and_Stop.setObjectName("Widget_Play_and_Stop")
        self.widget = QtWidgets.QWidget(self.Widget_Play_and_Stop)
        self.widget.setGeometry(QtCore.QRect(31, 15, 262, 33))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PlayButton = QtWidgets.QLabel(self.widget)
        self.PlayButton.setMaximumSize(QtCore.QSize(41, 31))
        self.PlayButton.setText("")
        self.PlayButton.setPixmap(QtGui.QPixmap("images/play.png"))
        self.PlayButton.setScaledContents(True)
        self.PlayButton.setObjectName("PlayButton")
        self.horizontalLayout.addWidget(self.PlayButton)
        self.StartPlay = QtWidgets.QPushButton(self.widget)
        self.StartPlay.setMaximumSize(QtCore.QSize(80, 25))
        self.StartPlay.setObjectName("StartPlay")
        self.horizontalLayout.addWidget(self.StartPlay)
        self.StopButton = QtWidgets.QLabel(self.widget)
        self.StopButton.setMaximumSize(QtCore.QSize(41, 31))
        self.StopButton.setText("")
        self.StopButton.setPixmap(QtGui.QPixmap("images/stop-button.png"))
        self.StopButton.setScaledContents(True)
        self.StopButton.setObjectName("StopButton")
        self.horizontalLayout.addWidget(self.StopButton)
        self.StopPlay = QtWidgets.QPushButton(self.widget)
        self.StopPlay.setMaximumSize(QtCore.QSize(80, 25))
        self.StopPlay.setObjectName("StopPlay")
        self.horizontalLayout.addWidget(self.StopPlay)
        self.verticalLayout_3.addWidget(self.Widget_Play_and_Stop)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LiveEditor = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.LiveEditor.setObjectName("LiveEditor")
        self.verticalLayout.addWidget(self.LiveEditor)
        self.InsertionMode = QtWidgets.QPushButton(self.centralwidget)
        self.InsertionMode.setObjectName("InsertionMode")
        self.verticalLayout.addWidget(self.InsertionMode)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.LiveVideo.setBuddy(self.Widget_Play_and_Stop)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SigNum.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#204a87;\">Sig</span><span style=\" font-size:24pt; color:#729fcf;\">Num</span></p></body></html>"))
        self.StartPlay.setText(_translate("MainWindow", "Play"))
        self.StopPlay.setText(_translate("MainWindow", "Stop"))
        self.InsertionMode.setText(_translate("MainWindow", "Switch to \'Insert Mode\'"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
