# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signum_playground.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 0, 0, 1, 1)
        self.w_vid = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.w_vid.setFont(font)
        self.w_vid.setAlignment(QtCore.Qt.AlignCenter)
        self.w_vid.setObjectName("w_vid")
        self.gridLayout_2.addWidget(self.w_vid, 1, 0, 1, 1)
        self.w_stop = QtWidgets.QPushButton(self.centralwidget)
        self.w_stop.setObjectName("w_stop")
        self.gridLayout_2.addWidget(self.w_stop, 2, 0, 1, 1)
        self.checkBoxes = QtWidgets.QVBoxLayout()
        self.checkBoxes.setObjectName("checkBoxes")
        self.letters = QtWidgets.QCheckBox(self.centralwidget)
        self.letters.setChecked(True)
        self.letters.setObjectName("letters")
        self.checkBoxes.addWidget(self.letters)
        self.numbers = QtWidgets.QCheckBox(self.centralwidget)
        self.numbers.setChecked(True)
        self.numbers.setObjectName("numbers")
        self.checkBoxes.addWidget(self.numbers)
        self.annotations = QtWidgets.QCheckBox(self.centralwidget)
        self.annotations.setChecked(True)
        self.annotations.setObjectName("annotations")
        self.checkBoxes.addWidget(self.annotations)
        self.gridLayout_2.addLayout(self.checkBoxes, 0, 1, 1, 1)
        self.inputCol = QtWidgets.QVBoxLayout()
        self.inputCol.setObjectName("inputCol")
        self.prediction = QtWidgets.QHBoxLayout()
        self.prediction.setObjectName("prediction")
        self.stat_prediction = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stat_prediction.setFont(font)
        self.stat_prediction.setObjectName("stat_prediction")
        self.prediction.addWidget(self.stat_prediction)
        self.current_prediction = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_prediction.sizePolicy().hasHeightForWidth())
        self.current_prediction.setSizePolicy(sizePolicy)
        self.current_prediction.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.current_prediction.setFont(font)
        self.current_prediction.setObjectName("current_prediction")
        self.prediction.addWidget(self.current_prediction)
        self.inputCol.addLayout(self.prediction)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.inputCol.addWidget(self.textBrowser)
        self.textBrowser_final = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_final.sizePolicy().hasHeightForWidth())
        self.textBrowser_final.setSizePolicy(sizePolicy)
        self.textBrowser_final.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_final.setFont(font)
        self.textBrowser_final.setObjectName("textBrowser_final")
        self.inputCol.addWidget(self.textBrowser_final)
        self.gridLayout_2.addLayout(self.inputCol, 1, 1, 1, 1)
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setObjectName("status")
        self.gridLayout_2.addWidget(self.status, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; color:#0055ff;\">Sig</span><span style=\" font-size:28pt; color:#00aaff;\">Num</span></p></body></html>"))
        self.w_vid.setText(_translate("MainWindow", "Initializing video stream."))
        self.w_stop.setText(_translate("MainWindow", "Stop Play"))
        self.letters.setText(_translate("MainWindow", "Letters"))
        self.numbers.setText(_translate("MainWindow", "Numbers"))
        self.annotations.setText(_translate("MainWindow", "Annotations"))
        self.stat_prediction.setText(_translate("MainWindow", "Prediction:"))
        self.current_prediction.setText(_translate("MainWindow", "Prediction"))
        self.status.setText(_translate("MainWindow", "Initializing..."))

